[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = ""
client_id = "235128743721-3635u0bpeni56ecnotjof0sgtmgqt1l0.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com /.well-known/openid-configuration"